### ISSUE TITLE
居中的常见实现

### ISSUE THREAD

**Issue by jiangshanmeta** [jiangshanmeta/jiangshanmeta.github.io#1]
## 水平居中

实现水平居中其实并不难，而且有多个可靠方案可以使用。

#### margin方案
用过bootstrap的人会很熟悉这么一个类名```.center-block```，这是实现居中的一个类名，具体实现是这样的

```CSS
.center-block{
	display:block;
	margin-left:auto;
	margin-right:auto;
}
```

#### 绝对定位方案

基本实现是这样的：

```CSS
.center-x-ab{
	position:absolute;
	left:50%;
	transform:translateX(-50%);
}
```

主要是应用了translate如果值为百分比，则参考于自身。如果为了水平居中而这么做就有点折腾了，然而这一方案可以扩展到垂直居中和水平垂直都居中。这样做的缺点是父元素需要处理子元素绝对定位带来的问题。在实践中，制作h5页面慎用这种方法居中，因为h5页面经常有动画，动画离不开transform,两者同时存在会看到很诡异的问题。

#### 文本居中方案

需要将要居中元素的父元素设定```text-align:center;```需要居中的元素的display要设定为```inline-block```,需要处理文本居中带来的影响，这一方案感觉用的不多。

#### flex方案

1.你为什么不用margin方案的方案

父元素 ```display:flex``` 子元素```margin-left:auto;margin-right:auto;```我的评价见小标题

2.感觉有点大材小用的方案

父元素div ```display:flex:justify-content:center;```评价如小标题
[上个例子](http://jiangshanmeta.github.io/tricks/animation_spin/index.html)

## 垂直居中

相较于水平居中，垂直居中相比较而言就有点难度了

#### 单行文字垂直居中

在我刚开始学习写页面的时候，就听说过让**line-height**和**height**值相等即可使单行文字垂直居中，最开始只是从使用的角度看这个问题，没有深入思考过，后来[张鑫旭大神告诉我们](http://t.imooc.com/learn/403)，这只是伪垂直居中。从工程实践角度这已经够用了，不要在意这些细节

#### 绝对定位方案

在水平居中中提到可以使用绝对定位实现水平居中，同样也可以使用绝对定位实现垂直居中：

```CSS
.center-y-ab{
	position:absolute;
	top:50%;
	transform:translateY(-50%);
}
```
虽然要处理绝对定位带来的后果，考虑到垂直居中方案并不多，这不失为一个好方案。

#### table方案

请参阅[这篇文章](https://css-tricks.com/centering-in-the-unknown/)

#### flex方案

父元素div ```display:flex``` 子元素img```margin-top:auto;margin-bottom:auto;```

当然你也可以折腾flex的相关属性去。

#### 绝对定位方案

```CSS
.center-xy-ab{
	position:absolute;
	top:50%;
	left:50%;
	transform:translate(-50%,-50%);
}
```

有代码有真相，就是结合水平、垂直居中的绝对定位方案

#### flex方案

父元素```display:flex;```

子元素```margin:auto;```

也不用去折腾各种对齐的属性

#### 水平文本居中 + 垂直table 的大杂烩

如果真考虑兼容性的话，这似乎是兼容性最好的方案了
然而，需要多写一层标签

## 基于视口的居中

常见的各种模态框基本上是相较于视口水平垂直居中的，其实我最早知道模态框的实现的时候它的居中是通过js计算得到的。作为 *能用CSS实现的就绝对不用js实现* 神教教徒，这个需求肯定要尝试使用CSS解决。

#### transform方案

基本上是上边的绝对定位方案的翻版
```CSS
.center-xy-viewport{
	position:fixed;
	top:50%;
	left:50%;
	transform:translate(-50%,-50%);
}
```
